### ISSUE TITLE
rm src/rxvtwcwidth.C: No such file

### ISSUE THREAD

**Issue by alpertuna** [blueyed/PKGBUILD-rxvt-unicode-wcwidthcallback#1]
Hello,
I tried it and it works perfectly. Now two wide glyps are displayed well. :+1:
However there is already no `src/rxvtwcwidth.C` file. That's why I commented that lines to install.

**Comment by blueyed** [comment]
Thanks, should be fixed now.

The patch applying is not optimal yet.  Will need to improve this.
It currently requires you to remove the already downloaded patch when updating it etc.

**Comment by blueyed** [comment]
There have been more updates today, and I've created a PR (against my own fork), to allow for code review etc: https://github.com/blueyed/rxvt-unicode/pull/1

**Comment by blueyed** [comment]
Added it to the AUR: https://aur.archlinux.org/packages/rxvt-unicode-wcwidthcallback.

**Comment by alpertuna** [comment]
Nice :+1:

**Comment by blueyed** [comment]
Great to have a fan already.. :)
